"""empty message

Revision ID: 0d3f59c967f2
Revises: 0b8cf654735e
Create Date: 2017-12-10 15:46:15.981439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3f59c967f2'
down_revision = '0b8cf654735e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choices', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('choices', sa.Column('modified_date', sa.DateTime(), nullable=False))
    op.add_column('part_of_speeches', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('part_of_speeches', sa.Column('modified_date', sa.DateTime(), nullable=False))
    op.add_column('words', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('words', sa.Column('modified_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'modified_date')
    op.drop_column('words', 'created_date')
    op.drop_column('part_of_speeches', 'modified_date')
    op.drop_column('part_of_speeches', 'created_date')
    op.drop_column('choices', 'modified_date')
    op.drop_column('choices', 'created_date')
    # ### end Alembic commands ###
