"""empty message

Revision ID: 4aa912b2e059
Revises: c2ead3b06880
Create Date: 2017-11-30 23:29:49.426449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa912b2e059'
down_revision = 'c2ead3b06880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=256), nullable=False),
    sa.Column('back', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('access_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    op.drop_table('words')
    # ### end Alembic commands ###
