"""empty message

Revision ID: 83e3a8c9a384
Revises: 4aa912b2e059
Create Date: 2017-12-01 23:49:03.193195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e3a8c9a384'
down_revision = '4aa912b2e059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_of_speeches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('words', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('words', sa.Column('part_of_speech', sa.Integer(), nullable=False))
    op.add_column('words', sa.Column('related_word_1', sa.String(length=256), nullable=False))
    op.add_column('words', sa.Column('related_word_2', sa.String(length=256), nullable=False))
    op.add_column('words', sa.Column('related_word_3', sa.String(length=256), nullable=False))
    op.add_column('words', sa.Column('wight', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'words', 'part_of_speeches', ['part_of_speech'], ['id'])
    op.create_foreign_key(None, 'words', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'wight')
    op.drop_column('words', 'related_word_3')
    op.drop_column('words', 'related_word_2')
    op.drop_column('words', 'related_word_1')
    op.drop_column('words', 'part_of_speech')
    op.drop_column('words', 'created_by')
    op.drop_table('part_of_speeches')
    # ### end Alembic commands ###
