"""empty message

Revision ID: a2c073252b1d
Revises: a5e68367f834
Create Date: 2017-12-04 22:17:19.275006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c073252b1d'
down_revision = 'a5e68367f834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=256), nullable=False),
    sa.Column('part_of_speech_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_of_speech_id'], ['part_of_speeches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('words', sa.Column('choice_1', sa.Integer(), nullable=False))
    op.add_column('words', sa.Column('choice_2', sa.Integer(), nullable=False))
    op.add_column('words', sa.Column('choice_3', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'words', 'choices', ['choice_3'], ['id'])
    op.create_foreign_key(None, 'words', 'choices', ['choice_2'], ['id'])
    op.create_foreign_key(None, 'words', 'choices', ['choice_1'], ['id'])
    op.drop_column('words', 'related_word_2')
    op.drop_column('words', 'related_word_1')
    op.drop_column('words', 'related_word_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('related_word_3', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('related_word_1', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('related_word_2', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'choice_3')
    op.drop_column('words', 'choice_2')
    op.drop_column('words', 'choice_1')
    op.drop_table('choices')
    # ### end Alembic commands ###
