"""empty message

Revision ID: a5e68367f834
Revises: a69f1d41d411
Create Date: 2017-12-03 09:58:27.217019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e68367f834'
down_revision = 'a69f1d41d411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'related_word_1',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('words', 'related_word_2',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('words', 'related_word_3',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'related_word_3',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('words', 'related_word_2',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('words', 'related_word_1',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
