"""empty message

Revision ID: a69f1d41d411
Revises: 83e3a8c9a384
Create Date: 2017-12-02 00:47:01.188293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69f1d41d411'
down_revision = '83e3a8c9a384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('part_of_speech_id', sa.Integer(), nullable=False))
    op.drop_constraint('words_part_of_speech_fkey', 'words', type_='foreignkey')
    op.create_foreign_key(None, 'words', 'part_of_speeches', ['part_of_speech_id'], ['id'])
    op.drop_column('words', 'part_of_speech')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('part_of_speech', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.create_foreign_key('words_part_of_speech_fkey', 'words', 'part_of_speeches', ['part_of_speech'], ['id'])
    op.drop_column('words', 'part_of_speech_id')
    # ### end Alembic commands ###
