"""empty message

Revision ID: d80710abdab8
Revises: 0d3f59c967f2
Create Date: 2018-01-04 00:27:13.071835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80710abdab8'
down_revision = '0d3f59c967f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
